import { reactive } from 'vue'
import { Card } from './models/Card.js'

// NOTE AppState is a reactive object to contain app level data
export const AppState = reactive({
  user: {},
  /**@type {import('./models/Account.js').Account} */
  account: {},
  profile: {},
  /**@type {import('./models/Card.js').Card} */
  cards: ([
    {
      "object": "card",
      "id": "14343e23-83fb-4d2e-a272-20d7787ef2ca",
      "oracle_id": "8e819d68-3a6e-449a-8392-e072724b80f1",
      "multiverse_ids": [
        391844
      ],
      "mtgo_id": 55680,
      "mtgo_foil_id": 55681,
      "tcgplayer_id": 95425,
      "cardmarket_id": 271713,
      "name": "Goblin Boom Keg",
      "lang": "en",
      "released_at": "2015-01-23",
      "uri": "https://api.scryfall.com/cards/14343e23-83fb-4d2e-a272-20d7787ef2ca",
      "scryfall_uri": "https://scryfall.com/card/frf/159/goblin-boom-keg?utm_source=api",
      "layout": "normal",
      "highres_image": true,
      "image_status": "highres_scan",
      "image_uris": {
        "small": "https://c1.scryfall.com/file/scryfall-cards/small/front/1/4/14343e23-83fb-4d2e-a272-20d7787ef2ca.jpg?1562822661",
        "normal": "https://c1.scryfall.com/file/scryfall-cards/normal/front/1/4/14343e23-83fb-4d2e-a272-20d7787ef2ca.jpg?1562822661",
        "large": "https://c1.scryfall.com/file/scryfall-cards/large/front/1/4/14343e23-83fb-4d2e-a272-20d7787ef2ca.jpg?1562822661",
        "png": "https://c1.scryfall.com/file/scryfall-cards/png/front/1/4/14343e23-83fb-4d2e-a272-20d7787ef2ca.png?1562822661",
        "art_crop": "https://c1.scryfall.com/file/scryfall-cards/art_crop/front/1/4/14343e23-83fb-4d2e-a272-20d7787ef2ca.jpg?1562822661",
        "border_crop": "https://c1.scryfall.com/file/scryfall-cards/border_crop/front/1/4/14343e23-83fb-4d2e-a272-20d7787ef2ca.jpg?1562822661"
      },
      "mana_cost": "{4}",
      "cmc": 4,
      "type_line": "Artifact",
      "oracle_text": "At the beginning of your upkeep, sacrifice Goblin Boom Keg.\nWhen Goblin Boom Keg is put into a graveyard from the battlefield, it deals 3 damage to any target.",
      "colors": [],
      "color_identity": [],
      "keywords": [],
      "legalities": {
        "standard": "not_legal",
        "future": "not_legal",
        "historic": "not_legal",
        "gladiator": "not_legal",
        "pioneer": "legal",
        "explorer": "not_legal",
        "modern": "legal",
        "legacy": "legal",
        "pauper": "not_legal",
        "vintage": "legal",
        "penny": "not_legal",
        "commander": "legal",
        "brawl": "not_legal",
        "historicbrawl": "not_legal",
        "alchemy": "not_legal",
        "paupercommander": "not_legal",
        "duel": "legal",
        "oldschool": "not_legal",
        "premodern": "not_legal"
      },
      "games": [
        "paper",
        "mtgo"
      ],
      "reserved": false,
      "foil": true,
      "nonfoil": true,
      "finishes": [
        "nonfoil",
        "foil"
      ],
      "oversized": false,
      "promo": false,
      "reprint": false,
      "variation": false,
      "set_id": "7bb5cb2b-081a-4c8c-b7e1-494046e6baa1",
      "set": "frf",
      "set_name": "Fate Reforged",
      "set_type": "expansion",
      "set_uri": "https://api.scryfall.com/sets/7bb5cb2b-081a-4c8c-b7e1-494046e6baa1",
      "set_search_uri": "https://api.scryfall.com/cards/search?order=set&q=e%3Afrf&unique=prints",
      "scryfall_set_uri": "https://scryfall.com/sets/frf?utm_source=api",
      "rulings_uri": "https://api.scryfall.com/cards/14343e23-83fb-4d2e-a272-20d7787ef2ca/rulings",
      "prints_search_uri": "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A8e819d68-3a6e-449a-8392-e072724b80f1&unique=prints",
      "collector_number": "159",
      "digital": false,
      "rarity": "uncommon",
      "flavor_text": "Dragonfire spawned many imitations. Some were more dramatic than others.",
      "card_back_id": "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
      "artist": "Viktor Titov",
      "artist_ids": [
        "2270c0b0-afb4-42b0-bcb6-25fe4ad6eef2"
      ],
      "illustration_id": "c3541493-5649-4a1b-bce5-db3515173cf2",
      "border_color": "black",
      "frame": "2015",
      "full_art": false,
      "textless": false,
      "booster": true,
      "story_spotlight": false,
      "edhrec_rank": 19783,
      "penny_rank": 4608,
      "prices": {
        "usd": "0.05",
        "usd_foil": "0.25",
        "usd_etched": null,
        "eur": "0.10",
        "eur_foil": "0.13",
        "tix": "0.03"
      },
      "related_uris": {
        "gatherer": "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=391844",
        "tcgplayer_infinite_articles": "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Goblin+Boom+Keg&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
        "tcgplayer_infinite_decks": "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Goblin+Boom+Keg&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
        "edhrec": "https://edhrec.com/route/?cc=Goblin+Boom+Keg"
      },
      "purchase_uris": {
        "tcgplayer": "https://www.tcgplayer.com/product/95425?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
        "cardmarket": "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Goblin+Boom+Keg&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
        "cardhoarder": "https://www.cardhoarder.com/cards/55680?affiliate_id=scryfall&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall"
      }
    },
    {
      "object": "card",
      "id": "dc36acc6-db4b-45b7-b526-7966ff82a44f",
      "oracle_id": "ad65bb8e-57de-49f3-ba7c-be62cf3fe3df",
      "multiverse_ids": [
        393960
      ],
      "tcgplayer_id": 93639,
      "cardmarket_id": 270000,
      "name": "Goblin Burrows",
      "lang": "en",
      "released_at": "2014-12-05",
      "uri": "https://api.scryfall.com/cards/dc36acc6-db4b-45b7-b526-7966ff82a44f",
      "scryfall_uri": "https://scryfall.com/card/evg/58/goblin-burrows?utm_source=api",
      "layout": "normal",
      "highres_image": true,
      "image_status": "highres_scan",
      "image_uris": {
        "small": "https://c1.scryfall.com/file/scryfall-cards/small/front/d/c/dc36acc6-db4b-45b7-b526-7966ff82a44f.jpg?1562939268",
        "normal": "https://c1.scryfall.com/file/scryfall-cards/normal/front/d/c/dc36acc6-db4b-45b7-b526-7966ff82a44f.jpg?1562939268",
        "large": "https://c1.scryfall.com/file/scryfall-cards/large/front/d/c/dc36acc6-db4b-45b7-b526-7966ff82a44f.jpg?1562939268",
        "png": "https://c1.scryfall.com/file/scryfall-cards/png/front/d/c/dc36acc6-db4b-45b7-b526-7966ff82a44f.png?1562939268",
        "art_crop": "https://c1.scryfall.com/file/scryfall-cards/art_crop/front/d/c/dc36acc6-db4b-45b7-b526-7966ff82a44f.jpg?1562939268",
        "border_crop": "https://c1.scryfall.com/file/scryfall-cards/border_crop/front/d/c/dc36acc6-db4b-45b7-b526-7966ff82a44f.jpg?1562939268"
      },
      "mana_cost": "",
      "cmc": 0,
      "type_line": "Land",
      "oracle_text": "{T}: Add {C}.\n{1}{R}, {T}: Target Goblin creature gets +2/+0 until end of turn.",
      "colors": [],
      "color_identity": [
        "R"
      ],
      "keywords": [],
      "produced_mana": [
        "C"
      ],
      "legalities": {
        "standard": "not_legal",
        "future": "not_legal",
        "historic": "not_legal",
        "gladiator": "not_legal",
        "pioneer": "not_legal",
        "explorer": "not_legal",
        "modern": "not_legal",
        "legacy": "legal",
        "pauper": "not_legal",
        "vintage": "legal",
        "penny": "legal",
        "commander": "legal",
        "brawl": "not_legal",
        "historicbrawl": "not_legal",
        "alchemy": "not_legal",
        "paupercommander": "not_legal",
        "duel": "legal",
        "oldschool": "not_legal",
        "premodern": "legal"
      },
      "games": [
        "paper",
        "mtgo"
      ],
      "reserved": false,
      "foil": false,
      "nonfoil": true,
      "finishes": [
        "nonfoil"
      ],
      "oversized": false,
      "promo": false,
      "reprint": true,
      "variation": false,
      "set_id": "d5dbdea8-45f6-4d22-990b-6b6897f99d18",
      "set": "evg",
      "set_name": "Duel Decks Anthology: Elves vs. Goblins",
      "set_type": "duel_deck",
      "set_uri": "https://api.scryfall.com/sets/d5dbdea8-45f6-4d22-990b-6b6897f99d18",
      "set_search_uri": "https://api.scryfall.com/cards/search?order=set&q=e%3Aevg&unique=prints",
      "scryfall_set_uri": "https://scryfall.com/sets/evg?utm_source=api",
      "rulings_uri": "https://api.scryfall.com/cards/dc36acc6-db4b-45b7-b526-7966ff82a44f/rulings",
      "prints_search_uri": "https://api.scryfall.com/cards/search?order=released&q=oracleid%3Aad65bb8e-57de-49f3-ba7c-be62cf3fe3df&unique=prints",
      "collector_number": "58",
      "digital": false,
      "rarity": "uncommon",
      "card_back_id": "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
      "artist": "David Martin",
      "artist_ids": [
        "996ad764-4ae0-4952-8bb5-5a75c9d68275"
      ],
      "illustration_id": "6bd5f5c8-246e-417f-9ecf-06450013ef03",
      "border_color": "black",
      "frame": "2015",
      "full_art": false,
      "textless": false,
      "booster": false,
      "story_spotlight": false,
      "edhrec_rank": 7234,
      "penny_rank": 5518,
      "prices": {
        "usd": "0.36",
        "usd_foil": null,
        "usd_etched": null,
        "eur": "0.25",
        "eur_foil": null,
        "tix": null
      },
      "related_uris": {
        "gatherer": "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=393960",
        "tcgplayer_infinite_articles": "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Goblin+Burrows&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
        "tcgplayer_infinite_decks": "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Goblin+Burrows&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
        "edhrec": "https://edhrec.com/route/?cc=Goblin+Burrows"
      },
      "purchase_uris": {
        "tcgplayer": "https://www.tcgplayer.com/product/93639?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
        "cardmarket": "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Goblin+Burrows&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
        "cardhoarder": "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Goblin+Burrows&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall"
      }
    },
    {
      "object": "card",
      "id": "b023c0cd-7046-418b-ad31-5c91c6930d45",
      "oracle_id": "c939e74d-4206-4ad1-bdaa-84103db0ac41",
      "multiverse_ids": [
        48215
      ],
      "mtgo_id": 20682,
      "mtgo_foil_id": 20683,
      "tcgplayer_id": 11800,
      "cardmarket_id": 496,
      "name": "Goblin Cannon",
      "lang": "en",
      "released_at": "2004-06-04",
      "uri": "https://api.scryfall.com/cards/b023c0cd-7046-418b-ad31-5c91c6930d45",
      "scryfall_uri": "https://scryfall.com/card/5dn/125/goblin-cannon?utm_source=api",
      "layout": "normal",
      "highres_image": true,
      "image_status": "highres_scan",
      "image_uris": {
        "small": "https://c1.scryfall.com/file/scryfall-cards/small/front/b/0/b023c0cd-7046-418b-ad31-5c91c6930d45.jpg?1562879198",
        "normal": "https://c1.scryfall.com/file/scryfall-cards/normal/front/b/0/b023c0cd-7046-418b-ad31-5c91c6930d45.jpg?1562879198",
        "large": "https://c1.scryfall.com/file/scryfall-cards/large/front/b/0/b023c0cd-7046-418b-ad31-5c91c6930d45.jpg?1562879198",
        "png": "https://c1.scryfall.com/file/scryfall-cards/png/front/b/0/b023c0cd-7046-418b-ad31-5c91c6930d45.png?1562879198",
        "art_crop": "https://c1.scryfall.com/file/scryfall-cards/art_crop/front/b/0/b023c0cd-7046-418b-ad31-5c91c6930d45.jpg?1562879198",
        "border_crop": "https://c1.scryfall.com/file/scryfall-cards/border_crop/front/b/0/b023c0cd-7046-418b-ad31-5c91c6930d45.jpg?1562879198"
      },
      "mana_cost": "{4}",
      "cmc": 4,
      "type_line": "Artifact",
      "oracle_text": "{2}: Goblin Cannon deals 1 damage to any target. Sacrifice Goblin Cannon.",
      "colors": [],
      "color_identity": [],
      "keywords": [],
      "legalities": {
        "standard": "not_legal",
        "future": "not_legal",
        "historic": "not_legal",
        "gladiator": "not_legal",
        "pioneer": "not_legal",
        "explorer": "not_legal",
        "modern": "legal",
        "legacy": "legal",
        "pauper": "not_legal",
        "vintage": "legal",
        "penny": "legal",
        "commander": "legal",
        "brawl": "not_legal",
        "historicbrawl": "not_legal",
        "alchemy": "not_legal",
        "paupercommander": "not_legal",
        "duel": "legal",
        "oldschool": "not_legal",
        "premodern": "not_legal"
      },
      "games": [
        "paper",
        "mtgo"
      ],
      "reserved": false,
      "foil": true,
      "nonfoil": true,
      "finishes": [
        "nonfoil",
        "foil"
      ],
      "oversized": false,
      "promo": false,
      "reprint": false,
      "variation": false,
      "set_id": "e4bc1b87-5476-463c-8640-4c414ecf1763",
      "set": "5dn",
      "set_name": "Fifth Dawn",
      "set_type": "expansion",
      "set_uri": "https://api.scryfall.com/sets/e4bc1b87-5476-463c-8640-4c414ecf1763",
      "set_search_uri": "https://api.scryfall.com/cards/search?order=set&q=e%3A5dn&unique=prints",
      "scryfall_set_uri": "https://scryfall.com/sets/5dn?utm_source=api",
      "rulings_uri": "https://api.scryfall.com/cards/b023c0cd-7046-418b-ad31-5c91c6930d45/rulings",
      "prints_search_uri": "https://api.scryfall.com/cards/search?order=released&q=oracleid%3Ac939e74d-4206-4ad1-bdaa-84103db0ac41&unique=prints",
      "collector_number": "125",
      "digital": false,
      "rarity": "uncommon",
      "flavor_text": "Goblin cannon crews are known not for their aim but for their ability to dive for cover.",
      "card_back_id": "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
      "artist": "Doug Chaffee",
      "artist_ids": [
        "dd587b27-dca3-4219-aa55-b285a7a77030"
      ],
      "illustration_id": "c70038ff-4d18-406b-ae5f-53fcd73e11ca",
      "border_color": "black",
      "frame": "2003",
      "full_art": false,
      "textless": false,
      "booster": true,
      "story_spotlight": false,
      "edhrec_rank": 10738,
      "penny_rank": 5564,
      "prices": {
        "usd": "0.21",
        "usd_foil": "10.66",
        "usd_etched": null,
        "eur": "0.02",
        "eur_foil": "0.70",
        "tix": "0.02"
      },
      "related_uris": {
        "gatherer": "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=48215",
        "tcgplayer_infinite_articles": "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Goblin+Cannon&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
        "tcgplayer_infinite_decks": "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Goblin+Cannon&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
        "edhrec": "https://edhrec.com/route/?cc=Goblin+Cannon"
      },
      "purchase_uris": {
        "tcgplayer": "https://www.tcgplayer.com/product/11800?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
        "cardmarket": "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Goblin+Cannon&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
        "cardhoarder": "https://www.cardhoarder.com/cards/20682?affiliate_id=scryfall&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall"
      }
    },
    {
      "object": "card",
      "id": "240344ff-404d-4894-a6e9-4401cd68cf50",
      "oracle_id": "c9b1557b-70b1-44f2-9fc2-7aa0b035b187",
      "multiverse_ids": [
        438497
      ],
      "tcgplayer_id": 149283,
      "cardmarket_id": 312362,
      "name": "Goblin Charbelcher",
      "lang": "en",
      "released_at": "2017-10-24",
      "uri": "https://api.scryfall.com/cards/240344ff-404d-4894-a6e9-4401cd68cf50",
      "scryfall_uri": "https://scryfall.com/card/ddt/57/goblin-charbelcher?utm_source=api",
      "layout": "normal",
      "highres_image": true,
      "image_status": "highres_scan",
      "image_uris": {
        "small": "https://c1.scryfall.com/file/scryfall-cards/small/front/2/4/240344ff-404d-4894-a6e9-4401cd68cf50.jpg?1592764888",
        "normal": "https://c1.scryfall.com/file/scryfall-cards/normal/front/2/4/240344ff-404d-4894-a6e9-4401cd68cf50.jpg?1592764888",
        "large": "https://c1.scryfall.com/file/scryfall-cards/large/front/2/4/240344ff-404d-4894-a6e9-4401cd68cf50.jpg?1592764888",
        "png": "https://c1.scryfall.com/file/scryfall-cards/png/front/2/4/240344ff-404d-4894-a6e9-4401cd68cf50.png?1592764888",
        "art_crop": "https://c1.scryfall.com/file/scryfall-cards/art_crop/front/2/4/240344ff-404d-4894-a6e9-4401cd68cf50.jpg?1592764888",
        "border_crop": "https://c1.scryfall.com/file/scryfall-cards/border_crop/front/2/4/240344ff-404d-4894-a6e9-4401cd68cf50.jpg?1592764888"
      },
      "mana_cost": "{4}",
      "cmc": 4,
      "type_line": "Artifact",
      "oracle_text": "{3}, {T}: Reveal cards from the top of your library until you reveal a land card. Goblin Charbelcher deals damage equal to the number of nonland cards revealed this way to any target. If the revealed land card was a Mountain, Goblin Charbelcher deals double that damage instead. Put the revealed cards on the bottom of your library in any order.",
      "colors": [],
      "color_identity": [],
      "keywords": [],
      "legalities": {
        "standard": "not_legal",
        "future": "not_legal",
        "historic": "not_legal",
        "gladiator": "not_legal",
        "pioneer": "not_legal",
        "explorer": "not_legal",
        "modern": "legal",
        "legacy": "legal",
        "pauper": "not_legal",
        "vintage": "legal",
        "penny": "not_legal",
        "commander": "legal",
        "brawl": "not_legal",
        "historicbrawl": "not_legal",
        "alchemy": "not_legal",
        "paupercommander": "not_legal",
        "duel": "legal",
        "oldschool": "not_legal",
        "premodern": "not_legal"
      },
      "games": [
        "paper"
      ],
      "reserved": false,
      "foil": false,
      "nonfoil": true,
      "finishes": [
        "nonfoil"
      ],
      "oversized": false,
      "promo": false,
      "reprint": true,
      "variation": false,
      "set_id": "c77df674-0ef5-47d9-ab22-56a6e1dc901c",
      "set": "ddt",
      "set_name": "Duel Decks: Merfolk vs. Goblins",
      "set_type": "duel_deck",
      "set_uri": "https://api.scryfall.com/sets/c77df674-0ef5-47d9-ab22-56a6e1dc901c",
      "set_search_uri": "https://api.scryfall.com/cards/search?order=set&q=e%3Addt&unique=prints",
      "scryfall_set_uri": "https://scryfall.com/sets/ddt?utm_source=api",
      "rulings_uri": "https://api.scryfall.com/cards/240344ff-404d-4894-a6e9-4401cd68cf50/rulings",
      "prints_search_uri": "https://api.scryfall.com/cards/search?order=released&q=oracleid%3Ac9b1557b-70b1-44f2-9fc2-7aa0b035b187&unique=prints",
      "collector_number": "57",
      "digital": false,
      "rarity": "rare",
      "card_back_id": "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
      "artist": "Jesper Ejsing",
      "artist_ids": [
        "a5f8354a-8b51-4e59-96b2-0e3aeae4fa1d"
      ],
      "illustration_id": "7faf93e7-0b8e-43b0-be5c-44c74ccf5ae4",
      "border_color": "black",
      "frame": "2015",
      "security_stamp": "oval",
      "full_art": false,
      "textless": false,
      "booster": false,
      "story_spotlight": false,
      "edhrec_rank": 7016,
      "prices": {
        "usd": "1.08",
        "usd_foil": null,
        "usd_etched": null,
        "eur": "0.45",
        "eur_foil": null,
        "tix": null
      },
      "related_uris": {
        "gatherer": "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=438497",
        "tcgplayer_infinite_articles": "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Goblin+Charbelcher&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
        "tcgplayer_infinite_decks": "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Goblin+Charbelcher&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
        "edhrec": "https://edhrec.com/route/?cc=Goblin+Charbelcher"
      },
      "purchase_uris": {
        "tcgplayer": "https://www.tcgplayer.com/product/149283?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
        "cardmarket": "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Goblin+Charbelcher&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
        "cardhoarder": "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Goblin+Charbelcher&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall"
      }
    },
    {
      "object": "card",
      "id": "d2ed2990-e5bf-4567-9a41-1846108a8aeb",
      "oracle_id": "8e69b322-4e66-4d5b-ab46-f002c40a913f",
      "multiverse_ids": [
        48077
      ],
      "mtgo_id": 19853,
      "mtgo_foil_id": 19854,
      "tcgplayer_id": 11491,
      "cardmarket_id": 177,
      "name": "Goblin Dirigible",
      "lang": "en",
      "released_at": "2003-10-02",
      "uri": "https://api.scryfall.com/cards/d2ed2990-e5bf-4567-9a41-1846108a8aeb",
      "scryfall_uri": "https://scryfall.com/card/mrd/177/goblin-dirigible?utm_source=api",
      "layout": "normal",
      "highres_image": true,
      "image_status": "highres_scan",
      "image_uris": {
        "small": "https://c1.scryfall.com/file/scryfall-cards/small/front/d/2/d2ed2990-e5bf-4567-9a41-1846108a8aeb.jpg?1562158871",
        "normal": "https://c1.scryfall.com/file/scryfall-cards/normal/front/d/2/d2ed2990-e5bf-4567-9a41-1846108a8aeb.jpg?1562158871",
        "large": "https://c1.scryfall.com/file/scryfall-cards/large/front/d/2/d2ed2990-e5bf-4567-9a41-1846108a8aeb.jpg?1562158871",
        "png": "https://c1.scryfall.com/file/scryfall-cards/png/front/d/2/d2ed2990-e5bf-4567-9a41-1846108a8aeb.png?1562158871",
        "art_crop": "https://c1.scryfall.com/file/scryfall-cards/art_crop/front/d/2/d2ed2990-e5bf-4567-9a41-1846108a8aeb.jpg?1562158871",
        "border_crop": "https://c1.scryfall.com/file/scryfall-cards/border_crop/front/d/2/d2ed2990-e5bf-4567-9a41-1846108a8aeb.jpg?1562158871"
      },
      "mana_cost": "{6}",
      "cmc": 6,
      "type_line": "Artifact Creature — Construct",
      "oracle_text": "Flying\nGoblin Dirigible doesn't untap during your untap step.\nAt the beginning of your upkeep, you may pay {4}. If you do, untap Goblin Dirigible.",
      "power": "4",
      "toughness": "4",
      "colors": [],
      "color_identity": [],
      "keywords": [
        "Flying"
      ],
      "legalities": {
        "standard": "not_legal",
        "future": "not_legal",
        "historic": "not_legal",
        "gladiator": "not_legal",
        "pioneer": "not_legal",
        "explorer": "not_legal",
        "modern": "legal",
        "legacy": "legal",
        "pauper": "not_legal",
        "vintage": "legal",
        "penny": "not_legal",
        "commander": "legal",
        "brawl": "not_legal",
        "historicbrawl": "not_legal",
        "alchemy": "not_legal",
        "paupercommander": "restricted",
        "duel": "legal",
        "oldschool": "not_legal",
        "premodern": "not_legal"
      },
      "games": [
        "paper",
        "mtgo"
      ],
      "reserved": false,
      "foil": true,
      "nonfoil": true,
      "finishes": [
        "nonfoil",
        "foil"
      ],
      "oversized": false,
      "promo": false,
      "reprint": false,
      "variation": false,
      "set_id": "1d4f90ba-8d4a-4ee5-bc2f-e2d6bffe4955",
      "set": "mrd",
      "set_name": "Mirrodin",
      "set_type": "expansion",
      "set_uri": "https://api.scryfall.com/sets/1d4f90ba-8d4a-4ee5-bc2f-e2d6bffe4955",
      "set_search_uri": "https://api.scryfall.com/cards/search?order=set&q=e%3Amrd&unique=prints",
      "scryfall_set_uri": "https://scryfall.com/sets/mrd?utm_source=api",
      "rulings_uri": "https://api.scryfall.com/cards/d2ed2990-e5bf-4567-9a41-1846108a8aeb/rulings",
      "prints_search_uri": "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A8e69b322-4e66-4d5b-ab46-f002c40a913f&unique=prints",
      "collector_number": "177",
      "digital": false,
      "rarity": "uncommon",
      "card_back_id": "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
      "artist": "Michael Sutfin",
      "artist_ids": [
        "5ce7b3bd-53d2-49e6-b504-37191e8e9b17"
      ],
      "illustration_id": "abec4fac-752a-48df-ae38-f2789c4a4b71",
      "border_color": "black",
      "frame": "2003",
      "full_art": false,
      "textless": false,
      "booster": true,
      "story_spotlight": false,
      "edhrec_rank": 22558,
      "prices": {
        "usd": "0.09",
        "usd_foil": "0.02",
        "usd_etched": null,
        "eur": "0.05",
        "eur_foil": "0.10",
        "tix": "0.03"
      },
      "related_uris": {
        "gatherer": "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=48077",
        "tcgplayer_infinite_articles": "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Goblin+Dirigible&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
        "tcgplayer_infinite_decks": "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Goblin+Dirigible&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
        "edhrec": "https://edhrec.com/route/?cc=Goblin+Dirigible"
      },
      "purchase_uris": {
        "tcgplayer": "https://www.tcgplayer.com/product/11491?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
        "cardmarket": "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Goblin+Dirigible&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
        "cardhoarder": "https://www.cardhoarder.com/cards/19853?affiliate_id=scryfall&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall"
      }
    },
    {
      "object": "card",
      "id": "951114fb-5ae5-4eb0-8e03-6e39b0b634b5",
      "oracle_id": "0709e9c8-dbe7-4806-ae75-d2e2d745d6a4",
      "multiverse_ids": [
        2405
      ],
      "tcgplayer_id": 4707,
      "cardmarket_id": 6506,
      "name": "Goblin Lyre",
      "lang": "en",
      "released_at": "1995-06-03",
      "uri": "https://api.scryfall.com/cards/951114fb-5ae5-4eb0-8e03-6e39b0b634b5",
      "scryfall_uri": "https://scryfall.com/card/ice/319/goblin-lyre?utm_source=api",
      "layout": "normal",
      "highres_image": true,
      "image_status": "highres_scan",
      "image_uris": {
        "small": "https://c1.scryfall.com/file/scryfall-cards/small/front/9/5/951114fb-5ae5-4eb0-8e03-6e39b0b634b5.jpg?1562922675",
        "normal": "https://c1.scryfall.com/file/scryfall-cards/normal/front/9/5/951114fb-5ae5-4eb0-8e03-6e39b0b634b5.jpg?1562922675",
        "large": "https://c1.scryfall.com/file/scryfall-cards/large/front/9/5/951114fb-5ae5-4eb0-8e03-6e39b0b634b5.jpg?1562922675",
        "png": "https://c1.scryfall.com/file/scryfall-cards/png/front/9/5/951114fb-5ae5-4eb0-8e03-6e39b0b634b5.png?1562922675",
        "art_crop": "https://c1.scryfall.com/file/scryfall-cards/art_crop/front/9/5/951114fb-5ae5-4eb0-8e03-6e39b0b634b5.jpg?1562922675",
        "border_crop": "https://c1.scryfall.com/file/scryfall-cards/border_crop/front/9/5/951114fb-5ae5-4eb0-8e03-6e39b0b634b5.jpg?1562922675"
      },
      "mana_cost": "{3}",
      "cmc": 3,
      "type_line": "Artifact",
      "oracle_text": "Sacrifice Goblin Lyre: Flip a coin. If you win the flip, Goblin Lyre deals damage to target opponent or planeswalker equal to the number of creatures you control. If you lose the flip, Goblin Lyre deals damage to you equal to the number of creatures that opponent or that planeswalker's controller controls.",
      "colors": [],
      "color_identity": [],
      "keywords": [],
      "legalities": {
        "standard": "not_legal",
        "future": "not_legal",
        "historic": "not_legal",
        "gladiator": "not_legal",
        "pioneer": "not_legal",
        "explorer": "not_legal",
        "modern": "not_legal",
        "legacy": "legal",
        "pauper": "not_legal",
        "vintage": "legal",
        "penny": "not_legal",
        "commander": "legal",
        "brawl": "not_legal",
        "historicbrawl": "not_legal",
        "alchemy": "not_legal",
        "paupercommander": "not_legal",
        "duel": "legal",
        "oldschool": "not_legal",
        "premodern": "legal"
      },
      "games": [
        "paper"
      ],
      "reserved": false,
      "foil": false,
      "nonfoil": true,
      "finishes": [
        "nonfoil"
      ],
      "oversized": false,
      "promo": false,
      "reprint": false,
      "variation": false,
      "set_id": "b0e08eea-5c01-4406-a6e2-dcd09c5e5b67",
      "set": "ice",
      "set_name": "Ice Age",
      "set_type": "expansion",
      "set_uri": "https://api.scryfall.com/sets/b0e08eea-5c01-4406-a6e2-dcd09c5e5b67",
      "set_search_uri": "https://api.scryfall.com/cards/search?order=set&q=e%3Aice&unique=prints",
      "scryfall_set_uri": "https://scryfall.com/sets/ice?utm_source=api",
      "rulings_uri": "https://api.scryfall.com/cards/951114fb-5ae5-4eb0-8e03-6e39b0b634b5/rulings",
      "prints_search_uri": "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A0709e9c8-dbe7-4806-ae75-d2e2d745d6a4&unique=prints",
      "collector_number": "319",
      "digital": false,
      "rarity": "rare",
      "card_back_id": "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
      "artist": "Mike Kimble",
      "artist_ids": [
        "06235390-cfc9-4418-827c-02d890bf54e5"
      ],
      "illustration_id": "a4909ec5-8db2-447d-a147-4aa4274168b9",
      "border_color": "black",
      "frame": "1993",
      "full_art": false,
      "textless": false,
      "booster": true,
      "story_spotlight": false,
      "edhrec_rank": 16308,
      "prices": {
        "usd": "0.31",
        "usd_foil": null,
        "usd_etched": null,
        "eur": "0.50",
        "eur_foil": null,
        "tix": null
      },
      "related_uris": {
        "gatherer": "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=2405",
        "tcgplayer_infinite_articles": "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Goblin+Lyre&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
        "tcgplayer_infinite_decks": "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Goblin+Lyre&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
        "edhrec": "https://edhrec.com/route/?cc=Goblin+Lyre"
      },
      "purchase_uris": {
        "tcgplayer": "https://www.tcgplayer.com/product/4707?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
        "cardmarket": "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Goblin+Lyre&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
        "cardhoarder": "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Goblin+Lyre&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall"
      }
    },
    {
      "object": "card",
      "id": "63282976-e08d-4b8c-bbfc-f6739fdaeaf9",
      "oracle_id": "0c5a7772-8358-4549-a583-f54246869e20",
      "multiverse_ids": [
        46049
      ],
      "mtgo_id": 19765,
      "mtgo_foil_id": 19766,
      "tcgplayer_id": 11492,
      "cardmarket_id": 178,
      "name": "Goblin Replica",
      "lang": "en",
      "released_at": "2003-10-02",
      "uri": "https://api.scryfall.com/cards/63282976-e08d-4b8c-bbfc-f6739fdaeaf9",
      "scryfall_uri": "https://scryfall.com/card/mrd/178/goblin-replica?utm_source=api",
      "layout": "normal",
      "highres_image": true,
      "image_status": "highres_scan",
      "image_uris": {
        "small": "https://c1.scryfall.com/file/scryfall-cards/small/front/6/3/63282976-e08d-4b8c-bbfc-f6739fdaeaf9.jpg?1562145936",
        "normal": "https://c1.scryfall.com/file/scryfall-cards/normal/front/6/3/63282976-e08d-4b8c-bbfc-f6739fdaeaf9.jpg?1562145936",
        "large": "https://c1.scryfall.com/file/scryfall-cards/large/front/6/3/63282976-e08d-4b8c-bbfc-f6739fdaeaf9.jpg?1562145936",
        "png": "https://c1.scryfall.com/file/scryfall-cards/png/front/6/3/63282976-e08d-4b8c-bbfc-f6739fdaeaf9.png?1562145936",
        "art_crop": "https://c1.scryfall.com/file/scryfall-cards/art_crop/front/6/3/63282976-e08d-4b8c-bbfc-f6739fdaeaf9.jpg?1562145936",
        "border_crop": "https://c1.scryfall.com/file/scryfall-cards/border_crop/front/6/3/63282976-e08d-4b8c-bbfc-f6739fdaeaf9.jpg?1562145936"
      },
      "mana_cost": "{3}",
      "cmc": 3,
      "type_line": "Artifact Creature — Goblin",
      "oracle_text": "{3}{R}, Sacrifice Goblin Replica: Destroy target artifact.",
      "power": "2",
      "toughness": "2",
      "colors": [],
      "color_identity": [
        "R"
      ],
      "keywords": [],
      "legalities": {
        "standard": "not_legal",
        "future": "not_legal",
        "historic": "not_legal",
        "gladiator": "not_legal",
        "pioneer": "not_legal",
        "explorer": "not_legal",
        "modern": "legal",
        "legacy": "legal",
        "pauper": "legal",
        "vintage": "legal",
        "penny": "not_legal",
        "commander": "legal",
        "brawl": "not_legal",
        "historicbrawl": "not_legal",
        "alchemy": "not_legal",
        "paupercommander": "legal",
        "duel": "legal",
        "oldschool": "not_legal",
        "premodern": "not_legal"
      },
      "games": [
        "paper",
        "mtgo"
      ],
      "reserved": false,
      "foil": true,
      "nonfoil": true,
      "finishes": [
        "nonfoil",
        "foil"
      ],
      "oversized": false,
      "promo": false,
      "reprint": false,
      "variation": false,
      "set_id": "1d4f90ba-8d4a-4ee5-bc2f-e2d6bffe4955",
      "set": "mrd",
      "set_name": "Mirrodin",
      "set_type": "expansion",
      "set_uri": "https://api.scryfall.com/sets/1d4f90ba-8d4a-4ee5-bc2f-e2d6bffe4955",
      "set_search_uri": "https://api.scryfall.com/cards/search?order=set&q=e%3Amrd&unique=prints",
      "scryfall_set_uri": "https://scryfall.com/sets/mrd?utm_source=api",
      "rulings_uri": "https://api.scryfall.com/cards/63282976-e08d-4b8c-bbfc-f6739fdaeaf9/rulings",
      "prints_search_uri": "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A0c5a7772-8358-4549-a583-f54246869e20&unique=prints",
      "collector_number": "178",
      "digital": false,
      "rarity": "common",
      "flavor_text": "It destroys with unthinking glee.",
      "card_back_id": "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
      "artist": "Carl Critchlow",
      "artist_ids": [
        "17948f16-611a-44b8-8d10-9895a0bdfff1"
      ],
      "illustration_id": "15d7dfe9-cc77-4993-b263-008afa50a7fc",
      "border_color": "black",
      "frame": "2003",
      "full_art": false,
      "textless": false,
      "booster": true,
      "story_spotlight": false,
      "edhrec_rank": 18164,
      "penny_rank": 10464,
      "prices": {
        "usd": "0.11",
        "usd_foil": "0.35",
        "usd_etched": null,
        "eur": "0.02",
        "eur_foil": "0.05",
        "tix": "0.02"
      },
      "related_uris": {
        "gatherer": "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=46049",
        "tcgplayer_infinite_articles": "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Goblin+Replica&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
        "tcgplayer_infinite_decks": "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Goblin+Replica&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
        "edhrec": "https://edhrec.com/route/?cc=Goblin+Replica"
      },
      "purchase_uris": {
        "tcgplayer": "https://www.tcgplayer.com/product/11492?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
        "cardmarket": "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Goblin+Replica&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
        "cardhoarder": "https://www.cardhoarder.com/cards/19765?affiliate_id=scryfall&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall"
      }
    },
    {
      "object": "card",
      "id": "7368a5ae-5642-4e90-9e73-9f0283067c15",
      "oracle_id": "506e4511-2982-40d7-948d-4b3a7fb68640",
      "multiverse_ids": [
        439574
      ],
      "tcgplayer_id": 153146,
      "cardmarket_id": 314025,
      "name": "Goblin Slingshot",
      "lang": "en",
      "released_at": "2017-12-08",
      "uri": "https://api.scryfall.com/cards/7368a5ae-5642-4e90-9e73-9f0283067c15",
      "scryfall_uri": "https://scryfall.com/card/ust/185/goblin-slingshot?utm_source=api",
      "layout": "normal",
      "highres_image": true,
      "image_status": "highres_scan",
      "image_uris": {
        "small": "https://c1.scryfall.com/file/scryfall-cards/small/front/7/3/7368a5ae-5642-4e90-9e73-9f0283067c15.jpg?1562919288",
        "normal": "https://c1.scryfall.com/file/scryfall-cards/normal/front/7/3/7368a5ae-5642-4e90-9e73-9f0283067c15.jpg?1562919288",
        "large": "https://c1.scryfall.com/file/scryfall-cards/large/front/7/3/7368a5ae-5642-4e90-9e73-9f0283067c15.jpg?1562919288",
        "png": "https://c1.scryfall.com/file/scryfall-cards/png/front/7/3/7368a5ae-5642-4e90-9e73-9f0283067c15.png?1562919288",
        "art_crop": "https://c1.scryfall.com/file/scryfall-cards/art_crop/front/7/3/7368a5ae-5642-4e90-9e73-9f0283067c15.jpg?1562919288",
        "border_crop": "https://c1.scryfall.com/file/scryfall-cards/border_crop/front/7/3/7368a5ae-5642-4e90-9e73-9f0283067c15.jpg?1562919288"
      },
      "mana_cost": "",
      "cmc": 0,
      "type_line": "Artifact — Contraption",
      "oracle_text": "Whenever you crank Goblin Slingshot, creatures you control get +2/+0 and gain trample until end of turn.",
      "colors": [],
      "color_identity": [],
      "keywords": [],
      "legalities": {
        "standard": "not_legal",
        "future": "not_legal",
        "historic": "not_legal",
        "gladiator": "not_legal",
        "pioneer": "not_legal",
        "explorer": "not_legal",
        "modern": "not_legal",
        "legacy": "not_legal",
        "pauper": "not_legal",
        "vintage": "not_legal",
        "penny": "not_legal",
        "commander": "not_legal",
        "brawl": "not_legal",
        "historicbrawl": "not_legal",
        "alchemy": "not_legal",
        "paupercommander": "not_legal",
        "duel": "not_legal",
        "oldschool": "not_legal",
        "premodern": "not_legal"
      },
      "games": [
        "paper"
      ],
      "reserved": false,
      "foil": true,
      "nonfoil": true,
      "finishes": [
        "nonfoil",
        "foil"
      ],
      "oversized": false,
      "promo": false,
      "reprint": false,
      "variation": false,
      "set_id": "83491685-880d-41dd-a4af-47d2b3b17c10",
      "set": "ust",
      "set_name": "Unstable",
      "set_type": "funny",
      "set_uri": "https://api.scryfall.com/sets/83491685-880d-41dd-a4af-47d2b3b17c10",
      "set_search_uri": "https://api.scryfall.com/cards/search?order=set&q=e%3Aust&unique=prints",
      "scryfall_set_uri": "https://scryfall.com/sets/ust?utm_source=api",
      "rulings_uri": "https://api.scryfall.com/cards/7368a5ae-5642-4e90-9e73-9f0283067c15/rulings",
      "prints_search_uri": "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A506e4511-2982-40d7-948d-4b3a7fb68640&unique=prints",
      "collector_number": "185",
      "digital": false,
      "rarity": "rare",
      "watermark": "goblinexplosioneers",
      "card_back_id": "98d277bf-8635-4a02-ac2f-4d44ddc47993",
      "artist": "Steve Prescott",
      "artist_ids": [
        "a1139fb8-41f5-4a9e-9a74-f662e1a23b35"
      ],
      "illustration_id": "cff65272-ea2c-401b-99e4-3cd716bf95df",
      "border_color": "borderless",
      "frame": "2015",
      "security_stamp": "oval",
      "full_art": false,
      "textless": false,
      "booster": true,
      "story_spotlight": false,
      "prices": {
        "usd": "0.19",
        "usd_foil": "1.96",
        "usd_etched": null,
        "eur": "0.15",
        "eur_foil": "1.55",
        "tix": null
      },
      "related_uris": {
        "gatherer": "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=439574",
        "tcgplayer_infinite_articles": "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Goblin+Slingshot&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
        "tcgplayer_infinite_decks": "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Goblin+Slingshot&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
        "edhrec": "https://edhrec.com/route/?cc=Goblin+Slingshot"
      },
      "purchase_uris": {
        "tcgplayer": "https://www.tcgplayer.com/product/153146?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
        "cardmarket": "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Goblin+Slingshot&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
        "cardhoarder": "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Goblin+Slingshot&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall"
      }
    },
    {
      "object": "card",
      "id": "229e8124-54ed-4c29-8c44-4962bd60f145",
      "oracle_id": "81a38340-9558-49d3-8de6-d7d01babfd97",
      "multiverse_ids": [
        46044
      ],
      "mtgo_id": 19759,
      "mtgo_foil_id": 19760,
      "tcgplayer_id": 11493,
      "cardmarket_id": 179,
      "name": "Goblin War Wagon",
      "lang": "en",
      "released_at": "2003-10-02",
      "uri": "https://api.scryfall.com/cards/229e8124-54ed-4c29-8c44-4962bd60f145",
      "scryfall_uri": "https://scryfall.com/card/mrd/179/goblin-war-wagon?utm_source=api",
      "layout": "normal",
      "highres_image": true,
      "image_status": "highres_scan",
      "image_uris": {
        "small": "https://c1.scryfall.com/file/scryfall-cards/small/front/2/2/229e8124-54ed-4c29-8c44-4962bd60f145.jpg?1562138261",
        "normal": "https://c1.scryfall.com/file/scryfall-cards/normal/front/2/2/229e8124-54ed-4c29-8c44-4962bd60f145.jpg?1562138261",
        "large": "https://c1.scryfall.com/file/scryfall-cards/large/front/2/2/229e8124-54ed-4c29-8c44-4962bd60f145.jpg?1562138261",
        "png": "https://c1.scryfall.com/file/scryfall-cards/png/front/2/2/229e8124-54ed-4c29-8c44-4962bd60f145.png?1562138261",
        "art_crop": "https://c1.scryfall.com/file/scryfall-cards/art_crop/front/2/2/229e8124-54ed-4c29-8c44-4962bd60f145.jpg?1562138261",
        "border_crop": "https://c1.scryfall.com/file/scryfall-cards/border_crop/front/2/2/229e8124-54ed-4c29-8c44-4962bd60f145.jpg?1562138261"
      },
      "mana_cost": "{4}",
      "cmc": 4,
      "type_line": "Artifact Creature — Juggernaut",
      "oracle_text": "Goblin War Wagon doesn't untap during your untap step.\nAt the beginning of your upkeep, you may pay {2}. If you do, untap Goblin War Wagon.",
      "power": "3",
      "toughness": "3",
      "colors": [],
      "color_identity": [],
      "keywords": [],
      "legalities": {
        "standard": "not_legal",
        "future": "not_legal",
        "historic": "not_legal",
        "gladiator": "not_legal",
        "pioneer": "not_legal",
        "explorer": "not_legal",
        "modern": "legal",
        "legacy": "legal",
        "pauper": "legal",
        "vintage": "legal",
        "penny": "legal",
        "commander": "legal",
        "brawl": "not_legal",
        "historicbrawl": "not_legal",
        "alchemy": "not_legal",
        "paupercommander": "legal",
        "duel": "legal",
        "oldschool": "not_legal",
        "premodern": "not_legal"
      },
      "games": [
        "paper",
        "mtgo"
      ],
      "reserved": false,
      "foil": true,
      "nonfoil": true,
      "finishes": [
        "nonfoil",
        "foil"
      ],
      "oversized": false,
      "promo": false,
      "reprint": false,
      "variation": false,
      "set_id": "1d4f90ba-8d4a-4ee5-bc2f-e2d6bffe4955",
      "set": "mrd",
      "set_name": "Mirrodin",
      "set_type": "expansion",
      "set_uri": "https://api.scryfall.com/sets/1d4f90ba-8d4a-4ee5-bc2f-e2d6bffe4955",
      "set_search_uri": "https://api.scryfall.com/cards/search?order=set&q=e%3Amrd&unique=prints",
      "scryfall_set_uri": "https://scryfall.com/sets/mrd?utm_source=api",
      "rulings_uri": "https://api.scryfall.com/cards/229e8124-54ed-4c29-8c44-4962bd60f145/rulings",
      "prints_search_uri": "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A81a38340-9558-49d3-8de6-d7d01babfd97&unique=prints",
      "collector_number": "179",
      "digital": false,
      "rarity": "common",
      "card_back_id": "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
      "artist": "Doug Chaffee",
      "artist_ids": [
        "dd587b27-dca3-4219-aa55-b285a7a77030"
      ],
      "illustration_id": "eb1ffd91-6ccb-465c-ae69-3e562212d337",
      "border_color": "black",
      "frame": "2003",
      "full_art": false,
      "textless": false,
      "booster": true,
      "story_spotlight": false,
      "edhrec_rank": 21209,
      "prices": {
        "usd": "0.06",
        "usd_foil": "0.25",
        "usd_etched": null,
        "eur": "0.01",
        "eur_foil": "0.05",
        "tix": "0.03"
      },
      "related_uris": {
        "gatherer": "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=46044",
        "tcgplayer_infinite_articles": "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Goblin+War+Wagon&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
        "tcgplayer_infinite_decks": "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Goblin+War+Wagon&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
        "edhrec": "https://edhrec.com/route/?cc=Goblin+War+Wagon"
      },
      "purchase_uris": {
        "tcgplayer": "https://www.tcgplayer.com/product/11493?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
        "cardmarket": "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Goblin+War+Wagon&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
        "cardhoarder": "https://www.cardhoarder.com/cards/19759?affiliate_id=scryfall&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall"
      }
    }
  ]).map(c => new Card(c)),
  decks: [],
  activeDeck: {},
  cardArts: [],
})
